CREATE TABLE TB_USUARIO(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_USUARIO VARCHAR(60),
IDADE_USUARIO INT,
EMAIL_USUARIO VARCHAR(50),
CPF_USUARIO VARCHAR(11),
GENERO_USUARIO VARCHAR (10),
SIGNO_USUARIO VARCHAR (20),
MAE_USUARIO VARCHAR (60),
PAI_USUARIO VARCHAR(60)
);